# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ngocando
tagline:          ngo does things
url:              http://ngocando.com
paginate:         1
baseurl:          /
author:
  name:           Richard Ngo
  url:            https://twitter.com/richardngo
  email:          thengocando@gmail.com
